:sparkles: Clean main distribution script
morpho-labs/morpho-rewards pull request #41
Opened 2022-12-03 02:49 UTC by julien-devatom

### Description of change
Basically, the only way from now to compute distributions was to running the tests, which is not really expected.
So that's the reason why I am adding two scripts:
- `yarn markets:emissions` is computing the markets emissions
- `yarn users:distribute` is computing the Merkle Tree for finished epochs

### Pull-Request Checklist

- [ ] Code is up-to-date with the `main` branch
- [ ] `yarn lint` passes with this change
- [ ] `yarn test` passes with this change
- [ ] This pull request links relevant issues as `Fixes #0000`
- [ ] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [ ] The new commits follow conventions outlined in the [conventional commit spec](https://www.conventionalcommits.org/en/v1.0.0/)

2022-12-04 10:19 UTC, MerlinEgalite requested changes

2022-12-04 10:19 UTC, MerlinEgalite commented on src/scripts/computeMarketsEmissions.ts
> +  );
More readable when there is space

2022-12-04 10:19 UTC, MerlinEgalite commented on src/scripts/computeMarketsEmissions.ts
> +        totalEmission: formatUnits(epoch.totalEmission),
I think the format is not the correct one here

2022-12-05 20:11 UTC, julien-devatom commented
> Looks fine, but please avoid force push else it's hard to see the diff

I've rebased on main, sry ser!

2022-12-05 20:16 UTC, merged